version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: rule-engine-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rule-engine-demo

volumes:
  mongodb_data:
